### ISSUE TITLE
No hint path defined for [filament-sanctum].

### ISSUE THREAD

**Issue by putheakhem** [devtical/filament-sanctum#1]
After Installing, I got this message "No hint path defined for [filament-sanctum]."

**Comment by EmilioBravo** [comment]
same here

**Comment by uzsoftic** [comment]
Any solution?

**Comment by gogo0618** [comment]
src/SanctumServiceProvider.php - should look like this, hasViews() is missing :
 public function configurePackage(Package $package): void
    {
        $package
            ->name('filament-sanctum')
            ->hasViews()
            ->hasConfigFile()
            ->hasAssets('filament-sanctum')
            ->hasTranslations();
    }
